# Generated by Django 3.0.3 on 2020-04-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('BName', models.CharField(max_length=20)),
                ('Publisher', models.CharField(max_length=20)),
                ('Version', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('Content', models.TextField(blank=True, default='无', null=True)),
                ('NumInLib', models.IntegerField(default=0)),
                ('NumNow', models.IntegerField(default=0)),
                ('Area', models.CharField(max_length=20)),
                ('Category', models.CharField(choices=[('1', '思政类'), ('2', '哲学类'), ('3', '社会科学类'), ('4', '军事类'), ('5', '经济类'), ('6', '文化科学类'), ('7', '语言文字类'), ('8', '文学类'), ('9', '艺术类'), ('10', '体育类'), ('11', '历史地理类'), ('12', '自然科学总论类'), ('13', '数理化学类'), ('14', '天文地球科学类'), ('15', '生物科学理类'), ('16', '医药类'), ('17', '农业科学类'), ('18', '工业技术类'), ('19', '交通运输类'), ('20', '航空航天类'), ('21', '环境科学类'), ('22', '计算机类'), ('23', '未分类')], default='未分类', max_length=30)),
                ('PubTime', models.DateField(default='1999-10-11')),
            ],
        ),
        migrations.CreateModel(
            name='BuyIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('AccountID', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Type', models.BooleanField(choices=[('1', True), ('2', False)], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('StudentID', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=20, unique=True)),
                ('Mail', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '保密')], default='保密', max_length=10)),
                ('SName', models.CharField(max_length=20)),
                ('School', models.CharField(choices=[('1', '信息技术与科学学院'), ('2', '材料科学与工程学院'), ('3', '机电工程学院'), ('4', '化学工程学院'), ('5', '经济管理学院'), ('6', '化学学院'), ('7', '数理学院'), ('8', '文法学院'), ('9', '生命科学与技术学院'), ('10', '继续教育学院'), ('11', '马克思主义学院'), ('12', '国际教育学院'), ('13', '侯德榜工程师学院'), ('14', '巴黎居里工程师学院')], default='信息技术与科学学院', max_length=20)),
                ('BLimit', models.IntegerField(default=3)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.User', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('ManagerID', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=20, unique=True)),
                ('Mail', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '保密')], default='保密', max_length=20)),
                ('MName', models.CharField(max_length=20)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.User', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowTime', models.DateField(default='1999-10-11')),
                ('BorrowDay', models.IntegerField(default=30)),
                ('ReNewTimes', models.IntegerField(default=3)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.Book', unique=True)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.Reader', unique=True)),
            ],
            options={
                'unique_together': {('StudentID', 'BookID')},
            },
        ),
    ]
