# Generated by Django 3.0.3 on 2020-04-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ReadTimes',
            field=models.IntegerField(default=0),
        ),
    ]
