# Generated by Django 3.0.3 on 2020-05-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='Class',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, to='BuctLib.ReaderClass'),
        ),
    ]
