# Generated by Django 3.0.3 on 2020-04-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0002_book_readtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='BookID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.Book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.Reader'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='AccountID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.User'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='AccountID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.User'),
        ),
    ]
