# Generated by Django 3.0.3 on 2020-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0002_auto_20200507_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='isAllowed',
            field=models.NullBooleanField(),
        ),
    ]
