# Generated by Django 3.0.3 on 2020-05-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0003_borrow_isallowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='MName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='SName',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='reader',
            name='Class',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.SET_DEFAULT, to='BuctLib.ReaderClass'),
        ),
    ]
