# Generated by Django 3.0.3 on 2020-04-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0003_auto_20200424_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookID',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
