# Generated by Django 3.0.3 on 2020-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0005_auto_20200508_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='Type',
            field=models.CharField(choices=[('1', '学生'), ('2', '教职工')], default='学生', max_length=10),
        ),
    ]
