# Generated by Django 3.0.3 on 2020-04-25 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0005_message_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='Time',
        ),
        migrations.AddField(
            model_name='notice',
            name='NTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='BorrowTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='MTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
