# Generated by Django 3.0.3 on 2020-04-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0006_auto_20200425_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='BookID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BuctLib.Book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BuctLib.Reader'),
        ),
    ]
