# Generated by Django 3.0.3 on 2020-05-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0006_auto_20200508_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
