# Generated by Django 3.0.3 on 2020-05-11 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0007_auto_20200508_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAllowed', models.NullBooleanField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.ReaderClass')),
                ('ReaderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.Reader')),
            ],
        ),
    ]
