# Generated by Django 3.0.3 on 2020-04-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0007_auto_20200425_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.BooleanField(choices=[('1', 'True'), ('2', 'False')], default=False),
        ),
    ]
