# Generated by Django 3.0.3 on 2020-05-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0008_applyclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyclass',
            name='Message',
            field=models.TextField(default=''),
        ),
    ]
