# Generated by Django 3.0.3 on 2020-04-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0009_auto_20200425_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Status',
            field=models.CharField(choices=[('1', '已读'), ('2', '未读')], default='未读', max_length=20),
        ),
    ]
