# Generated by Django 3.0.3 on 2020-05-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0009_applyclass_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyclass',
            name='isAllowed',
        ),
    ]
