# Generated by Django 3.0.3 on 2020-05-11 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0010_remove_applyclass_isallowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ReaderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuctLib.Reader'),
        ),
    ]
