# Generated by Django 3.0.3 on 2020-04-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0010_auto_20200425_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='NumInLib',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='NumNow',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='BorrowDay',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.SlugField(max_length=40),
        ),
    ]
