# Generated by Django 3.0.3 on 2020-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0011_auto_20200425_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Area',
            field=models.CharField(choices=[('图书馆一层', '图书馆一层'), ('图书馆二层', '图书馆二层'), ('图书馆三层', '图书馆三层'), ('图书馆四层', '图书馆四层')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('保密', '保密')], default='保密', max_length=20),
        ),
        migrations.AlterField(
            model_name='reader',
            name='Gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('保密', '保密')], default='保密', max_length=10),
        ),
    ]
