# Generated by Django 3.0.3 on 2020-05-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0011_auto_20200511_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ReaderClass',
            name='Days',
            field=models.PositiveSmallIntegerField(default=30, null=True),
        ),
    ]
