# Generated by Django 3.0.3 on 2020-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0012_remove_readerclass_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Price',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
