# Generated by Django 3.0.3 on 2020-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0012_auto_20200426_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('管理员', '管理员'), ('读者', '读者')], default='读者', max_length=20),
        ),
    ]
