# Generated by Django 3.0.3 on 2020-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0013_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.FloatField(default=30.0),
        ),
    ]
