# Generated by Django 3.0.3 on 2020-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0013_auto_20200426_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Area',
            field=models.CharField(choices=[('1', '图书馆一层'), ('2', '图书馆二层'), ('3', '图书馆三层'), ('4', '图书馆四层')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '保密')], default='保密', max_length=20),
        ),
        migrations.AlterField(
            model_name='reader',
            name='Gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '保密')], default='保密', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('1', '管理员'), ('2', '读者')], default='读者', max_length=20),
        ),
    ]
