# Generated by Django 3.0.3 on 2020-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0014_auto_20200426_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=40),
        ),
    ]
