# Generated by Django 3.0.3 on 2020-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0015_auto_20200512_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='Title',
            field=models.CharField(max_length=10),
        ),
    ]
