# Generated by Django 3.0.3 on 2020-04-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0015_auto_20200427_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='MName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='SName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
