# Generated by Django 3.0.3 on 2020-05-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0017_auto_20200512_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.CharField(choices=[('思政类', '思政类'), ('哲学类', '哲学类'), ('社会科学类', '社会科学类'), ('军事类', '军事类'), ('经济类', '经济类'), ('文化科学类', '文化科学类'), ('语言文字类', '语言文字类'), ('文学类', '文学类'), ('艺术类', '艺术类'), ('体育类', '体育类'), ('历史地理类', '历史地理类'), ('自然科学总论类', '自然科学总论类'), ('数理化学类', '数理化学类'), ('天文地球科学类', '天文地球科学类'), ('生物科学理类', '生物科学理类'), ('医药类', '医药类'), ('农业科学类', '农业科学类'), ('工业技术类', '工业技术类'), ('交通运输类', '交通运输类'), ('航空航天类', '航空航天类'), ('环境科学类', '环境科学类'), ('计算机类', '计算机类'), ('未分类', '未分类')], default='未分类', max_length=30),
        ),
    ]
