# Generated by Django 3.0.3 on 2020-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0019_borrow_isreturned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='isReturned',
        ),
        migrations.AddField(
            model_name='borrow',
            name='isLegal',
            field=models.BooleanField(default=True),
        ),
    ]
