# Generated by Django 3.0.3 on 2020-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0020_auto_20200516_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='isReturned',
            field=models.BooleanField(default=False),
        ),
    ]
