# Generated by Django 3.0.3 on 2020-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0021_borrow_isreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='RealreturnDay',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
