# Generated by Django 3.0.3 on 2020-05-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuctLib', '0025_auto_20200520_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerclass',
            name='Class',
            field=models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
