INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','计算机科学导论', '瞿中', '清华大学出版社',0, 79.9, 21, 20, '计算机类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','算法导论', '未知', '清华大学出版社',0, 79.9, 21, 20, '计算机类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','科学发现纵横谈', '王梓坤', '中国少年儿童出版社',0, 69.9, 30, 30, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','现代社会中的科学', '潘世墨', '浙江科学技术出版社',0,56.9, 25, 25, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','领导科学', '黄强', '高等教育出版社',0,89.9, 26, 26, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','科学家与科学道德', '杨德荣', '四川教育出版社',0,68.9, 24, 24, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','伊斯兰教育与科学', '周国黎', '中国社会科学出版社',0, 69.9, 23, 23, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','新科学', '维柯', '商务印书馆', 0, 88.9, 22, 22, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','科学偶然故事', '陈仁政', '江苏科学技术出版社',0,89.9, 18, 18, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','社会科学概览', '陈必滔', '福建人民出版社',0,68.9, 20, 20, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','中国科学', '中国科学院', '科学出版社',0, 59.9, 23, 23, '文化科学类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','军事', '麦家', '长江文艺出版社',0,79.9, 20, 19, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','军事科学研究与管理', '刘继贤', '军事科学出版社',0, 89.9, 30, 30, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','国民军事学', '石铎', '大东书局',0,  68.9, 25, 25, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','简明军事技术词典', '刘绍球', '湖南人民出版社',0,89.9, 26, 26, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','邓小平军事生涯', '郝智慧', '解放军出版社',0, 68.9, 24, 23, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','中国军事思想概论', '李铁民', '海潮出版社',0, 69.9, 23, 23, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','军队大脑', '沙波什尼科夫', '解放军出版社',0, 56.9, 22, 22, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','军事战略', '索科洛夫斯基', '战士出版社',0, 89.9, 18, 18, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','军事理论教程', '吴温暖', '高等教育出版社',0, 68.9, 20, 20, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','军事人才价值研究', '王鲁军', '军事科学出版社',0,59.9, 23, 23, '军事类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','经济法', '曾咏梅', '武汉大学出版社',0, 68.9, 23, 23, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','微观经济学纵横谈', ' 梁小民', '三联书店',0,  69.9, 22, 22, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','经济人类学', ' 陈庆德', '人民出版社',0, 88.9, 18, 18, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','管理经济学', '李宝山', '东北财经大学出版社',0, 89.9, 20, 20, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','综观经济学', '魏双凤', ' 广东高等教育出版社',0, 68.9, 23, 23, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','西方经济学', '臧良运', ' 科学出版社',0, 12.8 ,20, 20, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','世界经济发展研究', '陈其人', '上海人民出版社',0, 79.9, 30, 30, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','全球化与经济安全', '龙文懋', '湖南人民出版社',0, 89.9, 25, 25, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','中国经济前景分析', '陈佳贵', '社会科学文献出版社',0,68.9, 26, 26, '经济类');
INSERT INTO BuctLib_book (PubTime,BName, Author, Publisher,ReadTimes,Price, NumInLib,NumNow, Category) VALUES ('1999-10-11','全球网络经济', '萧琛', '华夏出版社',0, 89.9, 24, 24, '经济类');
